name: C# Code Review Bot Test0317-9

on:
  pull_request:
    workflow_run:
      workflows: ["Build Pull Request TEST"]
      types:
        - completed
    branches:
    - DevelNUI
    paths:
      - 'src/Tizen.NUI/**'  # src 폴더 내 파일 변경 시 실행
      - 'src/Tizen.NUI.Components/**'  # src 폴더 내 파일 변경 시 실행

  workflow_dispatch:

jobs:
  NUIStyleReview:
    runs-on: ubuntu-20.04
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: .NET SDK 설치
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # 최신 LTS 버전 사용

      - name: Code Analysis 실행 (Roslyn Analyzers)
        run: |
          echo "### START ###"
          pwd
          echo "=========================="
          dotnet build ./src/Tizen.NUI/Tizen.NUI.csproj /p:NuiRoslynAnalysis=true > result.txt 2>&1
          echo "=========================="
          ls -al
          echo "### END ###"

      - name: 워닝 에러 표시를 위해 파일에서 찾기
        run: |
          KEYWORD="Error(s)"  # 검색할 단어
          FILE_PATH="result.txt"  # 검색할 파일
          MATCHED_LINES=$(grep -C 1 "$KEYWORD" "$FILE_PATH" || echo "No matches found")
          echo "MATCHED_LINES<<EOF" >> $GITHUB_ENV
          echo "$MATCHED_LINES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: 업로드 file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-file
          path: result.txt

      - name: PR에 리뷰 코멘트 남기기
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const matchedLines = process.env.MATCHED_LINES;
            const commentBody = matchedLines !== "No matches found"
              ? "${matchedLines}\n"
              : "NONE\n";
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "NUI 스타일 체크 결과: " + commentBody + "[whole log download](https://github.com/" + context.repo.owner + "/" + context.repo.repo + "/actions/runs/" + process.env.GITHUB_RUN_ID + ")"
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
